name: Build project

on:
  push:
    branches-ignore:
      - release
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x ./gradlew
          CI=true ./gradlew :publishToMavenLocal --stacktrace --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ~/.m2/repository/
