name: Publish Release

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  publish:
    name: Build & Publish
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - name: Build & Publish to Maven
        env:
          MAVEN_RELEASE_USERNAME: ${{ secrets.MAVEN_RELEASE_USERNAME }}
          MAVEN_RELEASE_PASSWORD: ${{ secrets.MAVEN_RELEASE_PASSWORD }}
        run: |
          chmod +x ./gradlew
          CI=true ./gradlew :publishToMavenLocal :publish --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ~/.m2/repository/
